# Site settings
title: Videofy
company: Videofy LLC.
author: Suriyaa Kudo

info_email: info@videofy.isc
contact_email: contact@videofy.isc
dev_email: dev@videofy.isc

description: View new music videos, movies, trailers and more on iSC.net Videos.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://isc-host.github.io/videos.isc/" # the base hostname & protocol for your site
files_url: http://isc-host.github.io/videos.isc/assets/
counter_url: data/counter/

repository: https://github.com/iSC-Host/videos.isc

googleanalytics: UA-XXXX
